---
- name: Ensure Cumulus @ Cambridge OpenStack nova flavors exist
  hosts: localhost
  tags:
    - flavors
  roles:
    - role: stackhpc.os-flavors
      os_flavors_venv: "{{ cumulus_venv }}"
      os_flavors_auth_type: "{{ openstack_auth_type }}"
      os_flavors_auth: "{{ openstack_auth }}"
      os_flavors: "{{ cumulus_flavors }}"
