---
- name: Generate Evolution of Darwin (EoD) software images
  hosts: localhost
  tags:
    - images
  roles:
    - role: stackhpc.os-images
      os_images_venv: "{{ eod_venv }}"
      os_images_cache: "{{ ansible_env.PWD }}/eod-config-image-cache"
      os_images_auth_type: "{{ openstack_auth_type }}"
      os_images_auth: "{{ openstack_auth }}"
      os_images_list: "{{ eod_images }}"
      os_images_elements: "{{ eod_image_elements }}"
      os_images_git_elements: "{{ eod_image_git_elements }}"
