---
###############################################################################
# Configuration of OpenStack user environment for Cumulus @ Cambridge.

# Path to create virtualenv in which to install python dependencies.
#cumulus_venv:

# List of OpenStack projects. Format is as required by the stackhpc.os-projects
# role.
cumulus_projects:
  - "{{ cumulus_demo_project }}"

# Definition of the cumulus demo project. Format is as required by the
# stackhpc.os-projects role.
cumulus_demo_project:
  name: demo
  description: Cumulus @ Cambridge demo project
  project_domain: default
  user_domain: default
  users: "{{ cumulus_resops_users }}"
  quotas: "{{ cumulus_unlimited_quotas }}"

# List of users in the cumulus ResOps team. Format is as required by the
# stackhpc.os-projects role.
cumulus_resops_users:
  - name: hpcgodd1
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37386366333266356464663865316538653361313830633036626436613432636361386463373139
      3530303436393137613263656530333465313861316336330a623562323161326330383237303061
      63663266383362336361666134313364653037623430363638363333346435366230613135623763
      3063346333353831650a373138346633663663343638656163346533663735626133306438363066
      6638
    roles: "{{ cumulus_admin_roles }}"

# List of roles to apply to admin users in the cumulus demo project.
cumulus_admin_roles:
  - admin
  - heat_stack_owner
  - monasca-user

# List of roles to apply to regular users in the cumulus demo project.
cumulus_user_roles:
  - heat_stack_owner
  - observer
  - monasca-read-only-user

# Dict of quotas to set for projects with unlimited resource quotas
cumulus_unlimited_quotas:
  cores: -1
  floating_ips: -1
  injected_files: -1
  injected_file_size: -1
  instances: -1
  key_pairs: -1
  fixed_ips: -1
  ram: -1
  secgroup_rules: -1
  secgroups: -1

###############################################################################
# Configuration of networks, subnets and routers for cumulus.

# List of networks in the cumulus system. Format is as required by the
# stackhpc.os-networks role.
cumulus_networks:
  - "{{ cumulus_network_external }}"
  - "{{ cumulus_network_internal }}"
  - "{{ cumulus_network_inspection }}"
  - "{{ cumulus_network_storage }}"
  - "{{ cumulus_network_demo_vlan }}"
  - "{{ cumulus_network_demo_vxlan }}"
  - "{{ cumulus_network_demo_hs_vlan }}"
  - "{{ cumulus_network_demo_provider }}"
  - "{{ cumulus_network_infiniband }}"

# cumulus external network name.
cumulus_network_external_name: "external"

# cumulus external network.
cumulus_network_external:
  name: "{{ cumulus_network_external_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 60
  shared: true
  external: true
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_external }}"

# cumulus external subnet.
cumulus_subnet_external:
  name: "{{ cumulus_network_external_name }}"
  project: "admin"
  cidr: "10.60.0.0/16"
  gateway_ip: "10.60.255.1"
  allocation_pool_start: "10.60.2.0"
  allocation_pool_end: "10.60.5.255"
  # TODO: Add host route to storage subnet.

# cumulus internal network name.
cumulus_network_internal_name: "internal"

# cumulus internal network.
cumulus_network_internal:
  name: "{{ cumulus_network_internal_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 65
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_internal }}"

# cumulus internal subnet.
cumulus_subnet_internal:
  name: "{{ cumulus_network_internal_name }}"
  project: "admin"
  cidr: "10.65.0.0/16"
  enable_dhcp: false
  allocation_pool_start: "10.65.0.2"
  allocation_pool_end: "10.65.0.4"

# cumulus inspection network name.
cumulus_network_inspection_name: "inspection-net"

# cumulus inspection network.
cumulus_network_inspection:
  name: "{{ cumulus_network_inspection_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 71
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_inspection }}"

# cumulus inspection subnet.
cumulus_subnet_inspection:
  name: "{{ cumulus_network_inspection_name }}"
  project: "admin"
  cidr: "10.71.0.0/16"
  enable_dhcp: false
  allocation_pool_start: "10.71.0.1"
  allocation_pool_end: "10.71.0.1"

# cumulus storage network name.
cumulus_network_storage_name: "storage"

# cumulus storage network.
cumulus_network_storage:
  name: "{{ cumulus_network_storage_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 66
  shared: true
  external: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_storage }}"

# cumulus storage subnet.
cumulus_subnet_storage:
  name: "{{ cumulus_network_storage_name }}"
  project: "admin"
  cidr: "10.66.0.0/16"
  allocation_pool_start: "10.66.2.0"
  allocation_pool_end: "10.66.2.255"

# cumulus demo VLAN network name.
cumulus_network_demo_vlan_name: "demo-vlan"

# cumulus demo VLAN network.
cumulus_network_demo_vlan:
  name: "{{ cumulus_network_demo_vlan_name }}"
  project: "{{ cumulus_demo_project.name }}"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_demo_vlan }}"

# cumulus demo VLAN subnet.
cumulus_subnet_demo_vlan:
  name: "{{ cumulus_network_demo_vlan_name }}"
  project: "{{ cumulus_demo_project.name }}"
  cidr: "10.0.0.0/24"
  gateway_ip: "10.0.0.1"
  allocation_pool_start: "10.0.0.2"
  allocation_pool_end: "10.0.0.254"

# cumulus demo VXLAN network name.
cumulus_network_demo_vxlan_name: "demo-vxlan"

# cumulus demo VXLAN network.
cumulus_network_demo_vxlan:
  name: "{{ cumulus_network_demo_vxlan_name }}"
  project: "{{ cumulus_demo_project.name }}"
  provider_network_type: "vxlan"
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_demo_vxlan }}"

# cumulus demo VXLAN subnet.
cumulus_subnet_demo_vxlan:
  name: "{{ cumulus_network_demo_vxlan_name }}"
  project: "{{ cumulus_demo_project.name }}"
  cidr: "10.1.0.0/24"
  gateway_ip: "10.1.0.1"
  allocation_pool_start: "10.1.0.2"
  allocation_pool_end: "10.1.0.254"

# cumulus demo provider VLAN network name.
cumulus_network_demo_provider_name: "demo-provider"

# cumulus demo provider VLAN
cumulus_network_demo_provider:
  name: "{{ cumulus_network_demo_provider_name }}"
  project: "{{ cumulus_demo_project.name }}"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 100
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_demo_provider }}"

# cumulus demo provider VLAN subnet
cumulus_subnet_demo_provider:
  name: "{{ cumulus_network_demo_provider_name }}"
  project: "{{ cumulus_demo_project.name }}"
  cidr: "10.100.0.0/16"
  gateway_ip: "10.100.0.1"
  allocation_pool_start: "10.100.1.0"
  allocation_pool_end: "10.100.99.255"
  host_routes:
    - destination: "10.66.0.0/16"
      nexthop: "10.100.0.2"

# cumulus demo high speed VLAN network name.
cumulus_network_demo_hs_vlan_name: "demo-hs-vlan"

# cumulus demo high speed VLAN network.
cumulus_network_demo_hs_vlan:
  name: "{{ cumulus_network_demo_hs_vlan_name }}"
  project: "{{ cumulus_demo_project.name }}"
  provider_network_type: "vlan"
  provider_physical_network: "physnet2"
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_demo_hs_vlan }}"

# cumulus demo high speed VLAN subnet.
cumulus_subnet_demo_hs_vlan:
  name: "{{ cumulus_network_demo_hs_vlan_name }}"
  project: "{{ cumulus_demo_project.name }}"
  cidr: "10.2.0.0/24"
  gateway_ip: "10.2.0.1"
  allocation_pool_start: "10.2.0.2"
  allocation_pool_end: "10.2.0.254"

# cumulus demo InfiniBand network name.
cumulus_network_infiniband_name: "infiniband"

# cumulus demo InfiniBand network.
cumulus_network_infiniband:
  name: "{{ cumulus_network_infiniband_name }}"
  project: "admin"
  provider_network_type: "flat"
  provider_physical_network: "physnet3"
  shared: true
  # Subnet configuration.
  subnets:
    - "{{ cumulus_subnet_infiniband }}"

# cumulus demo InfiniBand subnet.
cumulus_subnet_infiniband:
  name: "{{ cumulus_network_infiniband_name }}"
  project: "admin"
  cidr: "10.3.0.0/16"
  enable_dhcp: false
  allocation_pool_start: "10.3.0.1"
  allocation_pool_end: "10.3.0.254"

# List of routers in the cumulus demo project. Format is as required by the
# stackhpc.os-networks role.
cumulus_routers:
  - "{{ cumulus_router_provision }}"
  - "{{ cumulus_router_cleaning }}"
  - "{{ cumulus_router_inspection }}"
  - "{{ cumulus_router_demo }}"

# cumulus bare metal provisioning router.
cumulus_router_provision:
  - name: "provision"
    project: "admin"
    interfaces:
      - net: "{{ cumulus_network_internal_name }}"
        subnet: "{{ cumulus_network_internal_name }}"
        portip: "10.65.0.2"
      - net: "provision-net"
        subnet: "provision-net"
        portip: "10.69.0.1"

# cumulus bare metal cleaning router.
cumulus_router_cleaning:
  - name: "cleaning"
    project: "admin"
    interfaces:
      - net: "{{ cumulus_network_internal_name }}"
        subnet: "{{ cumulus_network_internal_name }}"
        portip: "10.65.0.3"
      - net: "cleaning-net"
        subnet: "cleaning-net"
        portip: "10.70.0.1"

# cumulus bare metal inspection router.
cumulus_router_inspection:
  - name: "inspection"
    project: "admin"
    interfaces:
      - net: "{{ cumulus_network_internal_name }}"
        subnet: "{{ cumulus_network_internal_name }}"
        portip: "10.65.0.4"
      - net: "inspection-net"
        subnet: "inspection-net"
        portip: "10.71.0.1"

# cumulus demo router.
cumulus_router_demo:
  - name: "{{ cumulus_demo_project.name }}"
    project: "{{ cumulus_demo_project.name }}"
    interfaces:
      - "{{ cumulus_network_demo_vlan_name }}"
      - "{{ cumulus_network_demo_vxlan_name }}"
      - "{{ cumulus_network_demo_hs_vlan_name }}"
      - "{{ cumulus_network_demo_provider_name }}"
    network: "{{ cumulus_network_external_name }}"

# List of security groups in the cumulus demo project. Format is as required by the
# stackhpc.os-networks role.
# FIXME: Security group rules cannot be assigned to another project, due to
# https://github.com/ansible/ansible/issues/34467, and be created when another
# group with the same name exists in a different project either, due to
# https://github.com/ansible/ansible/issues/30292. These issues will be fixed
# by https://github.com/ansible/ansible/pull/34472 when it is merged. Until
# then, you can use the issue-34467 branch of the stackhpc ansible repo to
# register groups (after uncommenting them):
# https://github.com/stackhpc/ansible/tree/issue-34467.
cumulus_security_groups: []
  # Default security group for the cumulus demo project.
  #- name: default
  #  #project: "{{ cumulus_demo_project.name }}"
  #  rules:
  #    # Allow ICMP (for ping, etc.).
  #    - protocol: icmp
  #    # Allow SSH.
  #    - protocol: tcp
  #      port_range_min: 22
  #      port_range_max: 22

###############################################################################
# Configuration of nova flavors for cumulus.

# List of nova flavors in the cumulus demo project. Format is as required by the
# stackhpc.os-flavors role.
cumulus_flavors:
  - "{{ cumulus_flavor_baremetal_A }}"
  - "{{ cumulus_flavor_m1_tiny }}"
  - "{{ cumulus_flavor_m1_small }}"
  - "{{ cumulus_flavor_m1_medium }}"
  - "{{ cumulus_flavor_m1_large }}"
  - "{{ cumulus_flavor_m1_xlarge }}"

# Bare metal compute node.
cumulus_flavor_baremetal_A:
  name: "baremetal-A"
  ram: 65536
  disk: 0
  vcpus: 64
  extra_specs:
    "resources:CUSTOM_BAREMETAL_A": 1
    "resources:VCPU": 0
    "resources:MEMORY_MB": 0
    "resources:DISK_GB": 0

# Virtual machine flavors.
cumulus_flavor_m1_tiny:
  name: "m1.tiny"
  ram: 512
  disk: 1
  vcpus: 1

cumulus_flavor_m1_small:
  name: "m1.small"
  ram: 2048
  disk: 20
  vcpus: 1

cumulus_flavor_m1_medium:
  name: "m1.medium"
  ram: 4096
  disk: 40
  vcpus: 2

cumulus_flavor_m1_large:
  name: "m1.large"
  ram: 8192
  disk: 40
  vcpus: 4

cumulus_flavor_m1_xlarge:
  name: "m1.xlarge"
  ram: 16384
  disk: 100
  vcpus: 8

###############################################################################
# Software images for cumulus

cumulus_images:
  - "{{ cumulus_image_centos }}"
  - "{{ cumulus_image_centos_ib }}"
  - "{{ cumulus_image_centos_ohpc }}"

# Latest CentOS image
cumulus_image_centos:
  name: "CentOS7.5"
  elements:
    - "centos7"
    - "epel"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
  properties:
    os_distro: "centos"
    os_version: "7.5"

# Latest CentOS image, with support for accessing the InfiniBand network.
cumulus_image_centos_ib:
  name: "CentOS7.5-IB"
  elements:
    - "centos7"
    - "epel"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
    - "systemd-modules-load"
  env:
    DIB_SYSTEMD_MODULES_LOAD_CONTENT: "{{ cumulus_systemd_modules_load_ipoib }}"
    DIB_YUM_REPO_CONF: "{{ cumulus_cloud_init_0_7_9_25_repo_file }}"
  properties:
    os_distro: "centos"
    os_version: "7.5"

# Latest CentOS image, with OpenHPC and support for accessing the InfiniBand network.
cumulus_image_centos_ohpc:
  name: "CentOS7.5-OpenHPC"
  elements:
    - "centos7"
    - "epel"
    - "openhpc"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
    - "systemd-modules-load"
  env:
    DIB_SYSTEMD_MODULES_LOAD_CONTENT: "{{ cumulus_systemd_modules_load_ipoib }}"
    DIB_YUM_REPO_CONF: "{{ cumulus_cloud_init_0_7_9_25_repo_file }}"
    DIB_OPENHPC_GRPLIST: "ohpc-base-compute ohpc-slurm-client 'InfiniBand Support'"
    DIB_OPENHPC_PKGLIST: "lmod-ohpc mrsh-ohpc lustre-client-ohpc mvapich2-gnu-ohpc ntp"
    DIB_OPENHPC_DELETE_REPO: "n"
  properties:
    os_distro: "centos"
    os_version: "7.5"


# This creates a git checkout in the local user's home directory
cumulus_image_stackhpc_elements: "{{ ansible_env.PWD }}/stackhpc-image-elements"

cumulus_image_git_elements:
  - repo: "https://github.com/stackhpc/stackhpc-image-elements.git"
    local: "{{ cumulus_image_stackhpc_elements }}"

# Path to include
cumulus_image_elements:
  - "{{ cumulus_image_stackhpc_elements }}/elements"

# Yum repository config file for cloud-init repo.
# This contains a patched cloud-init package with support for configuring IP
# over Infiniband interfaces defined in a config drive.
cumulus_cloud_init_0_7_9_25_repo_file: "{{ playbook_dir }}/files/cloud-init-0.7.9-25.repo"

# Systemd modules-load.d file content for loading IPoIB interfaces:
cumulus_systemd_modules_load_ipoib: |
  # Load the IP over IB module prior to running cloud-init --local.
  ib_ipoib
  # Load the Mellanox IB driver.
  mlx4_ib
